server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # API → проксируем на бэкенд
    location /api/ {
        proxy_pass         http://backend:8000/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   Authorization     $http_authorization;
        proxy_pass_header  Authorization;
    }

    # mainpage
    location = / {
        try_files /mainpage/index.html =404;
    }

    # admin
    location /admin {
        index login.html;
        try_files $uri $uri/ /admin/login.html;
    }

    # static
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}