server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    #mainpage
    location = / {
        try_files /mainpage/index.html =404;
    }

    #admin
    location = /admin/ {
        try_files /admin/admin.html =404;
    }

    #static
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}