services:

  # PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: fixright_db
    restart: unless-stopped
    environment:
      POSTGRES_DB:       ${DB_NAME}
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  #backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fixright_backend
    restart: unless-stopped
    environment:
      DB_HOST:     db
      DB_PORT:     5432
      DB_NAME:     ${DB_NAME}
      DB_USER:     ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ADMIN_USERNAME:  ${ADMIN_USERNAME}
      ADMIN_PASSWORD:  ${ADMIN_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app

  #frontend
  frontend:
    image: nginx:alpine
    container_name: fixright_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  postgres_data: